main: main.c hypercube_functions.c pxp_functions.c helper_functions.c functions.h 
	gcc ./main.c ./hypercube_functions.c pxp_functions.c helper_functions.c -lgsl -lgslcblas -lm -W -Wall -Wextra -O3 -o main
